export default [
    {"label": "PromptCategory.Label.Common", "prompts": [
      {"label": "PromptText.Common.Masterpieces", "value": "masterpiece"},
      {"label": "PromptText.Common.Best picture quality", "value": "best quality"},
      {"label": "PromptText.Common.Higher quality", "value": "official art, extremely detailed CG unity 8k wallpaper"},
      {"label": "PromptText.Common.High Detail", "value": "highly detailed"},
      {"label": "PromptText.Common.Ultra High Resolution", "value": "absurdres"},
      {"label": "PromptText.Common.8k resolution", "value": "8k resolution"},
      {"label": "PromptText.Common.Depth of field", "value": "Depth of field"},
      {"label": "PromptText.Common.Exquisite features", "value": "exquisite facial features"},
      {"label": "PromptText.Common.Perfect face", "value": "prefect face"},
      {"label": "PromptText.Common.Glowing Skin", "value": "shiny skin"},
      {"label": "PromptText.Common.Abstract background", "value": "abstract background"},
      {"label": "PromptText.Common.Steampunk", "value": "steampunk"},
      {"label": "PromptText.Common.Cyberpunk", "value": "cyberpunk"},
      {"label": "PromptText.Common.Panorama", "value": "Panorama"},
      {"label": "PromptText.Common.Telephoto Lens", "value": "telephoto lens"},
      {"label": "PromptText.Common.Macro Lens", "value": "macro lens"},
      {"label": "PromptText.Common.Full Body Lens", "value": "full body"},
      {"label": "PromptText.Common.Medium Lens", "value": "medium shot"},
      {"label": "PromptText.Common.Sepia Lens", "value": "cowboy shot"},
      {"label": "PromptText.Common.Half Body Portrait", "value": "(profile picture)"},
      {"label": "PromptText.Common.Realistic Portrait", "value": "close up portrait"},
      {"label": "PromptText.Common.First-person view", "value": "POV"},
      {"label": "PromptText.Common.Fisheye lens", "value": "fisheye"},
      {"label": "PromptText.Common.Partial underwater shot", "value": "partially underwater shot"},
    ]},
    {"label": "PromptCategory.Label.Characters", "prompts": [
      {"label": "PromptText.Characters.Female", "value": "female"},
      {"label": "PromptText.Characters.Male", "value": "male"},
      {"label": "PromptText.Characters.Girl", "value": "girl"},
      {"label": "PromptText.Characters.Boy", "value": "boy"},
      {"label": "PromptText.Characters.Cute", "value": "shota"},
      {"label": "PromptText.Characters.Lolita", "value": "loli"},
      {"label": "PromptText.Characters.Beautiful girl", "value": "bishoujo"},
      {"label": "PromptText.Characters.Beautiful boy", "value": "bishounen"},
      {"label": "PromptText.Characters.hot girl", "value": "gyaru"},
      {"label": "PromptText.Characters.mature girl", "value": "mature female"},
      {"label": "PromptText.Characters.Missy", "value": "ojousama"},
      {"label": "PromptText.Characters.Q character", "value": "chibi"},
      {"label": "PromptText.Characters.Fatty", "value": "fat man"},
      {"label": "PromptText.Characters.Fake girls", "value": "crossdressing"},
      {"label": "PromptText.Characters.Angel", "value": "angel"},
      {"label": "PromptText.Characters.Devil", "value": "devil"},
      {"label": "PromptText.Characters.Single", "value": "solo"},
      {"label": "PromptText.Characters.Mini Girl", "value": "minigirl"},
      {"label": "PromptText.Characters.Multiple girls", "value": "multiple girls"},
      {"label": "PromptText.Characters.Non-human", "value": "no_humans"},
      {"label": "PromptText.Characters.Female Kid", "value": "mesugaki"},
      {"label": "PromptText.Characters.Monster", "value": "monster"},
      {"label": "PromptText.Characters.Old man", "value": "elder"},
      {"label": "PromptText.Characters.rich man", "value": "rich man"},
      {"label": "PromptText.Characters.beggar", "value": "beggar"},
      {"label": "PromptText.Characters.Giant", "value": "titans"},
      {"label": "PromptText.Characters.Dwarf", "value": "dwarf"},
      {"label": "PromptText.Characters.Clown", "value": "clown"},
      {"label": "PromptText.Characters.Slave", "value": "slave"},
      {"label": "PromptText.Characters.Snow Maiden", "value": "yukiwo"},
      {"label": "PromptText.Characters.Chief", "value": "sheik"},
      {"label": "PromptText.Characters.Queen", "value": "queen"},
      {"label": "PromptText.Characters.Goddess", "value": "goddess"},
      {"label": "PromptText.Characters.Princess", "value": "princess"},
      {"label": "PromptText.Characters.Prince", "value": "prince"},
      {"label": "PromptText.Characters.Bride", "value": "bride"},
      {"label": "PromptText.Characters.Groom", "value": "bridegroom"},
      {"label": "PromptText.Characters.Muscle man", "value": "muscle man"},
      {"label": "PromptText.Characters.Idol", "value": "idol"},
      {"label": "PromptText.Characters.Bunny Girl", "value": "bunny girl"},
      {"label": "PromptText.Characters.Monster Girl", "value": "monster girl"},
      {"label": "PromptText.Characters.Fox Girl", "value": "fox girl"},
      {"label": "PromptText.Characters.Wolf Girl", "value": "wolf girl"},
      {"label": "PromptText.Characters.Cat Girl", "value": "cat girl"},
      {"label": "PromptText.Characters.Twins", "value": "twins"},
      {"label": "PromptText.Characters.Triplets", "value": "triplets"},
      {"label": "PromptText.Characters.Siblings", "value": "brother and sister"},
      {"label": "PromptText.Characters.Puppets", "value": "marionette"},
      {"label": "PromptText.Characters.Clay hand puppets", "value": "nendoroid"},
      {"label": "PromptText.Characters.Lifeguard", "value": "lifeguard"},
      {"label": "PromptText.Characters.Boxer", "value": "boxer"},
      {"label": "PromptText.Characters.Scientist", "value": "scientist"},
      {"label": "PromptText.Characters.Athletes", "value": "athletes"},
      {"label": "PromptText.Characters.Workplace women", "value": "office lady"},
    ]},
    {"label": "PromptCategory.Label.Role", "prompts": [
      {"label": "PromptText.Role.Monk", "value": "monk"},
      {"label": "PromptText.Role.Acrobats", "value": "crobat"},
      {"label": "PromptText.Role.Pokémon", "value": "pokemon"},
      {"label": "PromptText.Role.Teddy Bear", "value": "teddy bear"},
      {"label": "PromptText.Role.Mario", "value": "mario"},
      {"label": "PromptText.Role.Pikachu", "value": "pikachu"},
      {"label": "PromptText.Role.New Century Evangelion", "value": "neon genesis evangelion"},
      {"label": "PromptText.Role.Hatsune Miku", "value": "hatsune miku"},
      {"label": "PromptText.Role.Harry Potter", "value": "harry potter"},
      {"label": "PromptText.Role.Doraemon", "value": "doraemon"},
      {"label": "PromptText.Role.Saint Seiya", "value": "saint seiya"},
      {"label": "PromptText.Role.Gojira Goku", "value": "gojou satoru"},
      {"label": "PromptText.Role.Avengers Alliance", "value": "avengers"},
      {"label": "PromptText.Role.Wonder Woman", "value": "mazinger "},
      {"label": "PromptText.Role.Captain America", "value": "captain america"},
      {"label": "PromptText.Role.Crayon Shin", "value": "crayon shin-chan"},
      {"label": "PromptText.Role.Slam Dunk Master", "value": "slam dunk"},
      {"label": "PromptText.Role.Sun Wukong", "value": "sun wukong"},
      {"label": "PromptText.Role.Witch", "value": "witch"},
      {"label": "PromptText.Role.Ninja", "value": "ninja"},
      {"label": "PromptText.Role.Sister", "value": "nun"},
      {"label": "PromptText.Role.Nurse", "value": "nurse"},
      {"label": "PromptText.Role.Flight attendant", "value": "stewardess"},
      {"label": "PromptText.Role.Student", "value": "student"},
      {"label": "PromptText.Role.Waitress", "value": "waitress"},
      {"label": "PromptText.Role.Vampire", "value": "vampire"},
      {"label": "PromptText.Role.Teacher", "value": "teacher"},
      {"label": "PromptText.Role.Racer", "value": "racer"},
      {"label": "PromptText.Role.Police officer", "value": "police"},
      {"label": "PromptText.Role.Soldier", "value": "soldier"},
      {"label": "PromptText.Role.Knight", "value": "knight"},
      {"label": "PromptText.Role.Magical girl", "value": "magical_girl"},
      {"label": "PromptText.Role.Orcs", "value": "orc"},
      {"label": "PromptText.Role.Cheerleaders", "value": "cheerleader"},
      {"label": "PromptText.Role.Male actors", "value": "actor"},
      {"label": "PromptText.Role.Actress", "value": "actress"},
      {"label": "PromptText.Role.spy", "value": "spy"},
      {"label": "PromptText.Role.secret agent", "value": "agent"},
      {"label": "PromptText.Role.Assassins", "value": "assassin"},
      {"label": "PromptText.Role.Poet", "value": "poet"},
      {"label": "PromptText.Role.Japanese Samurai", "value": "samurai"},
      {"label": "PromptText.Role.Druid", "value": "druid"},
      {"label": "PromptText.Role.Dancer", "value": "dancing girl"},
      {"label": "PromptText.Role.Motorcyclist", "value": "motorcyclist"},
      {"label": "PromptText.Role.Hacker", "value": "hacker"},
      {"label": "PromptText.Role.Magician", "value": "magician"},
      {"label": "PromptText.Role.Detective", "value": "detective"},
      {"label": "PromptText.Role.Mannequin", "value": "doll"},
      {"label": "PromptText.Role.Goblin", "value": "elf"},
      {"label": "PromptText.Role.Pixie", "value": "fairy"},
      {"label": "PromptText.Role.Orcs1", "value": "furry"},
      {"label": "PromptText.Role.Maid", "value": "maid"},
      {"label": "PromptText.Role.Mermaid", "value": "mermaid"},
      {"label": "PromptText.Role.Pilot", "value": "pilot"},
      {"label": "PromptText.Role.Diver", "value": "diver"},
      {"label": "PromptText.Role.Bar censor", "value": "bar censor"},
      {"label": "PromptText.Role.Preacher", "value": "missionary"},
      {"label": "PromptText.Role.Masked Rider", "value": "kamen rider"},
      {"label": "PromptText.Role.Fireman", "value": "firefighter"},
      {"label": "PromptText.Role.Gatekeeper", "value": "goalkeeper"},
      {"label": "PromptText.Role.Cook", "value": "chef"},
      {"label": "PromptText.Role.Astronaut", "value": "astronaut"},
      {"label": "PromptText.Role.Magician1", "value": "magister"},
      {"label": "PromptText.Role.Spider-Man", "value": "spider-man"},
      {"label": "PromptText.Role.Santa Claus", "value": "santa alter"},
      {"label": "PromptText.Role.Cashier", "value": "cashier"},
      {"label": "PromptText.Role.Mailman", "value": "mailman"},
      {"label": "PromptText.Role.Barista", "value": "barista"},
      {"label": "PromptText.Role.Hermit", "value": "the hermit"},
      {"label": "PromptText.Role.Shepherd", "value": "makihitsuji"},
    ]},
    {"label": "PromptCategory.Label.Face", "prompts": [
      {"label": "PromptText.Face.Thick eyebrows", "value": "thick eyebrows"},
      {"label": "PromptText.Face.Hollow Eyes", "value": "empty eyes"},
      {"label": "PromptText.Face.Wide-eyed", "value": "wide eyes"},
      {"label": "PromptText.Face.Chestnut Mouth", "value": "chestnut mouth"},
      {"label": "PromptText.Face.Animal ears", "value": "fake animal ears"},
      {"label": "PromptText.Face.Beard", "value": "beard"},
      {"label": "PromptText.Face.Moustache", "value": "mustache"},
      {"label": "PromptText.Face.Goatee", "value": "goatee"},
      {"label": "PromptText.Face.Long sideburns", "value": "long sideburns"},
      {"label": "PromptText.Face.Eyebrows cocked", "value": "cocked eyebrow"},
      {"label": "PromptText.Face.Short eyebrows", "value": "short eyebrows"},
      {"label": "PromptText.Face.Thick lips", "value": "thick lips"},
      {"label": "PromptText.Face.Puffy lips", "value": "puffy lips"},
      {"label": "PromptText.Face.Lipstick", "value": "lipstick"},
      {"label": "PromptText.Face.Heart-shaped mouth", "value": "heart-shaped mouth"},
      {"label": "PromptText.Face.Pouting lips", "value": "pout"},
      {"label": "PromptText.Face.Open Mouth", "value": "open mouth"},
      {"label": "PromptText.Face.Shut up", "value": "closed mouth"},
      {"label": "PromptText.Face.Close one eye", "value": "one eye closed"},
      {"label": "PromptText.Face.Half-closed eye", "value": "half-closed eyes"},
      {"label": "PromptText.Face.Sharp teeth", "value": "fangs"},
      {"label": "PromptText.Face.Tiger teeth", "value": "canine teeth"},
      {"label": "PromptText.Face.Clench your teeth", "value": "clenched teeth"},
      {"label": "PromptText.Face.Cat_s mouth", "value": "：3"},
      {"label": "PromptText.Face.Shark mouth", "value": "shark mouth"},
      {"label": "PromptText.Face.Cat ears", "value": "cat ears"},
      {"label": "PromptText.Face.Dog ears", "value": "dog ears"},
      {"label": "PromptText.Face.Fox ears", "value": "fox ears"},
      {"label": "PromptText.Face.Rabbit ears", "value": "bunny ears"},
      {"label": "PromptText.Face.Bear Ears", "value": "bear ears"},
      {"label": "PromptText.Face.Gradient Eyes", "value": "gradient_eyes"},
      {"label": "PromptText.Face.Large watery eyes", "value": "aqua eyes"},
      {"label": "PromptText.Face.V-shaped eyebrows", "value": "v-shaped eyebrows"},
      {"label": "PromptText.Face.Rolling white eyes", "value": "rolling eyes"},
      {"label": "PromptText.Face.crossed eyes", "value": "cross-eyed"},
      {"label": "PromptText.Face.Cat eyes", "value": "slit pupils"},
      {"label": "PromptText.Face.Bloodshot eyes", "value": "bloodshot eyes"},
      {"label": "PromptText.Face.Glowing eyes", "value": "glowing eyes"},
      {"label": "PromptText.Face.Hanging eyes", "value": "tsurime"},
      {"label": "PromptText.Face.Droopy eyes", "value": "tareme"},
      {"label": "PromptText.Face.Demon eyes", "value": "devil eyes"},
      {"label": "PromptText.Face.Constricted pupils", "value": "constricted pupils"},
      {"label": "PromptText.Face.Devil_s pupil", "value": "devil pupils"},
      {"label": "PromptText.Face.Snake pupil", "value": "snake pupils"},
      {"label": "PromptText.Face.Glittering pupil", "value": "pupils sparkling"},
      {"label": "PromptText.Face.Flower-shaped pupil", "value": "flower-shaped pupils"},
      {"label": "PromptText.Face.Love pupil", "value": "heart-shaped pupils"},
      {"label": "PromptText.Face.Heterochromatic pupils", "value": "heterochromia"},
      {"label": "PromptText.Face.Beauty Pupil", "value": "color contact lenses"},
      {"label": "PromptText.Face.Long eyelashes", "value": "longeyelashes"},
      {"label": "PromptText.Face.Colored eyelashes", "value": "colored eyelashes"},
      {"label": "PromptText.Face.Under Eye Mole", "value": "mole under eye"},
      {"label": "PromptText.Face.Tongue out", "value": ":p"},
      {"label": "PromptText.Face.Separate lips", "value": "parted lips"},
      {"label": "PromptText.Face.Moles under the mouth", "value": "mole under mouth"},
    ]},
    {"label": "PromptCategory.Label.Expressions", "prompts": [
      {"label": "PromptText.Expressions.Expressionless", "value": "expressionless"},
      {"label": "PromptText.Expressions.Pale face", "value": "turn pale"},
      {"label": "PromptText.Expressions.2D blushing", "value": "blush stickers"},
      {"label": "PromptText.Expressions.Red face", "value": "blush"},
      {"label": "PromptText.Expressions.Both eyes straight", "value": "blank stare"},
      {"label": "PromptText.Expressions.veins bulging", "value": "anger vein"},
      {"label": "PromptText.Expressions.embarrassed", "value": "embarrassed"},
      {"label": "PromptText.Expressions.arrogant", "value": "hubrael"},
      {"label": "PromptText.Expressions.depressed", "value": "depressed"},
      {"label": "PromptText.Expressions.smiling", "value": "light smile"},
      {"label": "PromptText.Expressions.fake smile", "value": "false smile"},
      {"label": "PromptText.Expressions.Teasing smile", "value": "seductive smile"},
      {"label": "PromptText.Expressions.Crazy smile", "value": "crazy smile"},
      {"label": "PromptText.Expressions.Evil smile", "value": "evil smile"},
      {"label": "PromptText.Expressions.One-sided mouth up", "value": "smirk"},
      {"label": "PromptText.Expressions.Seductive smile", "value": "seductive smile"},
      {"label": "PromptText.Expressions.Scowl", "value": "wince"},
      {"label": "PromptText.Expressions.Troubled", "value": "kilesha"},
      {"label": "PromptText.Expressions.Gloomy face", "value": "shaded face"},
      {"label": "PromptText.Expressions.Pain", "value": "pain"},
      {"label": "PromptText.Expressions.Scream", "value": "screaming"},
      {"label": "PromptText.Expressions.Sigh", "value": "sigh"},
      {"label": "PromptText.Expressions.Tension", "value": "nervous"},
      {"label": "PromptText.Expressions.Confused", "value": "confused"},
      {"label": "PromptText.Expressions.Fear", "value": "scared"},
      {"label": "PromptText.Expressions.smile with teeth", "value": "grin"},
      {"label": "PromptText.Expressions.Laughing", "value": "laughing"},
      {"label": "PromptText.Expressions.Drunk", "value": "drunk"},
      {"label": "PromptText.Expressions.Crying", "value": "tears"},
      {"label": "PromptText.Expressions.Sad", "value": "sad"},
      {"label": "PromptText.Expressions.Angry", "value": "angry"},
      {"label": "PromptText.Expressions.Cup smiley", "value": ":d"},
      {"label": "PromptText.Expressions.shy", "value": "nose blush"},
      {"label": "PromptText.Expressions.serious", "value": "serious"},
      {"label": "PromptText.Expressions.contemptuous", "value": "jitome"},
      {"label": "PromptText.Expressions.Crazy", "value": "crazy"},
      {"label": "PromptText.Expressions.blackened", "value": "dark_persona"},
      {"label": "PromptText.Expressions.smug", "value": "smug"},
      {"label": "PromptText.Expressions.in thought", "value": "thinking"},
      {"label": "PromptText.Expressions.raising an eyebrow", "value": "raised eyebrow"},
      {"label": "PromptText.Expressions.Frowning lightly", "value": "light frown"},
      {"label": "PromptText.Expressions.frowning", "value": "frown"},
      {"label": "PromptText.Expressions.Mischievous face", "value": "naughty face"},
      {"label": "PromptText.Expressions.Making a face", "value": "eyeid pull"},
      {"label": "PromptText.Expressions.nosebleed", "value": "nosebleed"},
      {"label": "PromptText.Expressions.sleepy", "value": "sleepy"},
      {"label": "PromptText.Expressions.Squinting", "value": "zzz"},
      {"label": "PromptText.Expressions.Drooling", "value": "drooling"},
    ]},
    {"label": "PromptCategory.Label.Hair", "prompts": [
      {"label": "PromptText.Hair.Short hair", "value": "short hair"},
      {"label": "PromptText.Hair.Medium hair", "value": "medium hair"},
      {"label": "PromptText.Hair.Long hair", "value": "long hair"},
      {"label": "PromptText.Hair.Hair past the shoulders", "value": "hair over shoulder"},
      {"label": "PromptText.Hair.White hair", "value": "white hair"},
      {"label": "PromptText.Hair.Bangs", "value": "bangs"},
      {"label": "PromptText.Hair.Short Ponytail", "value": "short ponytail"},
      {"label": "PromptText.Hair.Side Ponytail", "value": "side ponytail"},
      {"label": "PromptText.Hair.Front Ponytail", "value": "front ponytail"},
      {"label": "PromptText.Hair.Split Ponytail", "value": "split ponytail"},
      {"label": "PromptText.Hair.Low Ponytail Defense", "value": "low twintails"},
      {"label": "PromptText.Hair.Short Ponytail Braid", "value": "short twintails"},
      {"label": "PromptText.Hair.Side Braid", "value": "side braid"},
      {"label": "PromptText.Hair.Hair Tie", "value": "tied hair"},
      {"label": "PromptText.Hair.Single Side Bun", "value": "single side bun"},
      {"label": "PromptText.Hair.Curly Hair", "value": "curly hair"},
      {"label": "PromptText.Hair.Straight Hair", "value": "straight hair"},
      {"label": "PromptText.Hair.Wavy Hair", "value": "wavy hair"},
      {"label": "PromptText.Hair.Bob", "value": "bob hair"},
      {"label": "PromptText.Hair.Side parting", "value": "slicked-back"},
      {"label": "PromptText.Hair.Reggae", "value": "Reggae hair"},
      {"label": "PromptText.Hair.Pompadour", "value": "pompadour"},
      {"label": "PromptText.Hair.Mohican", "value": "Mohawk"},
      {"label": "PromptText.Hair.Pot Head", "value": "bowl cut"},
      {"label": "PromptText.Hair.Nerd Hair", "value": "ahoge"},
      {"label": "PromptText.Hair.Antenna Nerdy Hair", "value": "antenna hair"},
      {"label": "PromptText.Hair.Heart Shaped Nerdy Hair", "value": "heart ahoge"},
      {"label": "PromptText.Hair.Crossed bangs", "value": "crossed bang"},
      {"label": "PromptText.Hair.Eyebrow Bangs", "value": "hair between eye"},
      {"label": "PromptText.Hair.Princess curls", "value": "drill hair"},
      {"label": "PromptText.Hair.Winged Hair", "value": "hair wings"},
      {"label": "PromptText.Hair.Puffy hair", "value": "disheveled hair"},
      {"label": "PromptText.Hair.Messy Hair", "value": "messy hair"},
      {"label": "PromptText.Hair.Braids", "value": "braid"},
      {"label": "PromptText.Hair.Double Braids", "value": "twin braids"},
      {"label": "PromptText.Hair.Ponytail", "value": "ponytail"},
      {"label": "PromptText.Hair.Braided Ponytail", "value": "braided ponytail"},
      {"label": "PromptText.Hair.French Braid", "value": "french braid"},
      {"label": "PromptText.Hair.Open Neck Coiffure", "value": "chignon"},
      {"label": "PromptText.Hair.Braided Buns", "value": "braided bun"},
      {"label": "PromptText.Hair.Bangs1", "value": "blunt bangs"},
      {"label": "PromptText.Hair.Angled Bangs", "value": "diagonal bangs"},
      {"label": "PromptText.Hair.Asymmetrical Bangs", "value": "asymmetrical bangs"},
      {"label": "PromptText.Hair.Braided Bangs", "value": "braided bangs"},
      {"label": "PromptText.Hair.Princess Cut", "value": "hime_cut"},
      {"label": "PromptText.Hair.Sister cut", "value": "bob cut"},
      {"label": "PromptText.Hair.Hedgehog Hair", "value": "spiked hair"},
      {"label": "PromptText.Hair.Coiffure Hair", "value": "updo"},
      {"label": "PromptText.Hair.Elf short hair", "value": "pixie cut"},
      {"label": "PromptText.Hair.Long hair locks", "value": "dreadlocks"},
      {"label": "PromptText.Hair.Exploding head", "value": "afro"},
      {"label": "PromptText.Hair.Bald", "value": "bald"},
      {"label": "PromptText.Hair.Blonde", "value": "blonde hair"},
      {"label": "PromptText.Hair.Silver hair", "value": "silver hair"},
      {"label": "PromptText.Hair.Grey hair", "value": "grey hair"},
      {"label": "PromptText.Hair.Brunette", "value": "brown hair"},
      {"label": "PromptText.Hair.Brunette1", "value": "black hair"},
      {"label": "PromptText.Hair.Purple hair", "value": "purple hair"},
      {"label": "PromptText.Hair.Red hair", "value": "red hair"},
      {"label": "PromptText.Hair.Blue hair", "value": "blue hair"},
      {"label": "PromptText.Hair.Green hair", "value": "green hair"},
      {"label": "PromptText.Hair.Pink hair", "value": "pink hair"},
      {"label": "PromptText.Hair.Orange Hair", "value": "orange hair"},
      {"label": "PromptText.Hair.Dyed", "value": "streaked hair"},
      {"label": "PromptText.Hair.Colored Hair", "value": "multicolored hair"},
      {"label": "PromptText.Hair.Rainbow hair", "value": "rainbow-like hair"},
      {"label": "PromptText.Hair.Double Balls", "value": "double bun"},
      {"label": "PromptText.Hair.High ponytail", "value": "high ponytail"},
      {"label": "PromptText.Hair.American style inch hair", "value": "buzz cut"},
      {"label": "PromptText.Hair.Big volume voluminous hair", "value": "big hair"},
      {"label": "PromptText.Hair.Shiny Hair", "value": "shiny hair"},
      {"label": "PromptText.Hair.Glowing hair", "value": "glowing hair"},
      {"label": "PromptText.Hair.Hair between the eyes", "value": "hair between eyes"},
      {"label": "PromptText.Hair.Teased Behind the Ears", "value": "hair behind ear"},
    ]},
    {"label": "PromptCategory.Label.Decoration", "prompts": [
      {"label": "PromptText.Decoration.Hair bands", "value": "hair ribbon"},
      {"label": "PromptText.Decoration.Bracelets", "value": "bracelet"},
      {"label": "PromptText.Decoration.Ribbons", "value": "ribbon"},
      {"label": "PromptText.Decoration.Collar", "value": "choker"},
      {"label": "PromptText.Decoration.Metal collars", "value": "metal collar"},
      {"label": "PromptText.Decoration.Rings", "value": "ring"},
      {"label": "PromptText.Decoration.Wristbands", "value": "wristband"},
      {"label": "PromptText.Decoration.Pendants", "value": "pendant"},
      {"label": "PromptText.Decoration.Brooches", "value": "brooch"},
      {"label": "PromptText.Decoration.Ribbon Trim", "value": "ribbon trim"},
      {"label": "PromptText.Decoration.Lace trim", "value": "lace trim"},
      {"label": "PromptText.Decoration.Skirt support", "value": "skirt lift"},
      {"label": "PromptText.Decoration.Hand guard", "value": "gauntlets"},
      {"label": "PromptText.Decoration.Neckties", "value": "neckerchief"},
      {"label": "PromptText.Decoration.Red scarf", "value": "red neckerchief"},
      {"label": "PromptText.Decoration.epaulettes", "value": "pauldrons"},
      {"label": "PromptText.Decoration.Armband", "value": "arm strap"},
      {"label": "PromptText.Decoration.Arm bracelets", "value": "armlet"},
      {"label": "PromptText.Decoration.Hoop earrings", "value": "hoop earrings"},
      {"label": "PromptText.Decoration.Thin Shoulder Strap", "value": "spaghetti strap"},
      {"label": "PromptText.Decoration.Prajna Mask", "value": "Prajna in mask"},
      {"label": "PromptText.Decoration.Bracelets1", "value": "bangle"},
      {"label": "PromptText.Decoration.Earrings", "value": "stud earrings"},
      {"label": "PromptText.Decoration.Veil", "value": "veil"},
      {"label": "PromptText.Decoration.Bridal Veil", "value": "bridal veil"},
      {"label": "PromptText.Decoration.Crowns", "value": "tiara"},
      {"label": "PromptText.Decoration.Mini Crown", "value": "mini crown"},
      {"label": "PromptText.Decoration.Headband", "value": "head scarf"},
      {"label": "PromptText.Decoration.Animal Headbands", "value": "animal hood"},
      {"label": "PromptText.Decoration.Earmuffs", "value": "ear covers"},
      {"label": "PromptText.Decoration.Rising Sun Shaped Jewelry", "value": "sunburst"},
      {"label": "PromptText.Decoration.Pearl bracelets", "value": "pearl bracelet"},
      {"label": "PromptText.Decoration.Aviator sunglasses", "value": "aviator sunglasses"},
      {"label": "PromptText.Decoration.Rimless Glasses", "value": "semi-rimless eyewear"},
      {"label": "PromptText.Decoration.Earrings1", "value": "drop earrings"},
      {"label": "PromptText.Decoration.Puppet Ring", "value": "puppet rings"},
      {"label": "PromptText.Decoration.Corsage", "value": "corsage"},
      {"label": "PromptText.Decoration.Sapphire Brooch", "value": "sapphire brooch"},
      {"label": "PromptText.Decoration.Bow Hair Accessories", "value": "hair bow"},
      {"label": "PromptText.Decoration.Crescent Moon Hair Accessories", "value": "crescent hair ornament"},
      {"label": "PromptText.Decoration.Lolita Hair Accessories", "value": "lolita hairband"},
      {"label": "PromptText.Decoration.Feather Hair Accessories", "value": "feather hair ornament"},
      {"label": "PromptText.Decoration.Head Flower", "value": "hair flower"},
      {"label": "PromptText.Decoration.Hair Buns", "value": "hair bun"},
      {"label": "PromptText.Decoration.Hair Clips", "value": "hairclip"},
      {"label": "PromptText.Decoration.Hair Bands", "value": "hair scrunchie"},
      {"label": "PromptText.Decoration.Hair Bands1", "value": "hair rings"},
      {"label": "PromptText.Decoration.Hair Accessories", "value": "hair ornament"},
      {"label": "PromptText.Decoration.Hair Sticks", "value": "hair stick"},
      {"label": "PromptText.Decoration.Heart Shaped Hair Accessories", "value": "heart hair ornament"},
      {"label": "PromptText.Decoration.Semi-rimless Glasses", "value": "semi-rimless eyewear"},
      {"label": "PromptText.Decoration.Sunglasses", "value": "sunglasses"},
      {"label": "PromptText.Decoration.Wind goggles", "value": "goggles"},
      {"label": "PromptText.Decoration.One-eye mask", "value": "eyepatch"},
      {"label": "PromptText.Decoration.Black Eye Glasses", "value": "black blindfold"},
      {"label": "PromptText.Decoration.Jewelry", "value": "jewelry"},
      {"label": "PromptText.Decoration.Necklace", "value": "necklace"},
      {"label": "PromptText.Decoration.Iron Thorn", "value": "metal thorns"},
      {"label": "PromptText.Decoration.Halo", "value": "halo"},
      {"label": "PromptText.Decoration.Mask", "value": "mouth mask"},
      {"label": "PromptText.Decoration.Band-Aids", "value": "bandaid hair ornament"},
      {"label": "PromptText.Decoration.Nail Polish", "value": "nail polish"},
      {"label": "PromptText.Decoration.Doll joints", "value": "doll joints"},
      {"label": "PromptText.Decoration.Mechanical Prosthetics", "value": " cybernetic prosthesis"},
      {"label": "PromptText.Decoration.Mechanical Legs", "value": "mechanical legs"},
      {"label": "PromptText.Decoration.Beach towel", "value": "beach towel"},
      {"label": "PromptText.Decoration.Rain poncho", "value": "poncho"},
      {"label": "PromptText.Decoration.Heavy makeup", "value": "make up"},
    ]},
    {"label": "PromptCategory.Label.Clothing", "prompts": [
      {"label": "PromptText.Clothing.Overhand sleeves", "value": "sleeves_past_fingers"},
      {"label": "PromptText.Clothing.Undershirt", "value": "tank top"},
      {"label": "PromptText.Clothing.Vest-style underwear", "value": "camisole"},
      {"label": "PromptText.Clothing.see-through clothing", "value": "transparent clothes"},
      {"label": "PromptText.Clothing.Tuxedo", "value": "tailcoat"},
      {"label": "PromptText.Clothing.Latex jumpsuit", "value": "latex bodysuit"},
      {"label": "PromptText.Clothing.Maid outfits", "value": "Victoria black maid dress"},
      {"label": "PromptText.Clothing.Denim shorts", "value": "denim shorts"},
      {"label": "PromptText.Clothing.Ruffles", "value": "frills"},
      {"label": "PromptText.Clothing.Lace", "value": "lace"},
      {"label": "PromptText.Clothing.White Shirt", "value": "white shirt"},
      {"label": "PromptText.Clothing.Sailor Shirt", "value": "sailor shirt"},
      {"label": "PromptText.Clothing.T-shirt", "value": "T-shirt"},
      {"label": "PromptText.Clothing.Sweater", "value": "sweater"},
      {"label": "PromptText.Clothing.Sailor Uniform", "value": "sailor suit"},
      {"label": "PromptText.Clothing.Student Uniform", "value": "school uniform"},
      {"label": "PromptText.Clothing.Workplace Uniform", "value": "bussiness suit"},
      {"label": "PromptText.Clothing.Suits", "value": "suit"},
      {"label": "PromptText.Clothing.Military Uniform", "value": "military uniform"},
      {"label": "PromptText.Clothing.Dresses", "value": "lucency full dress"},
      {"label": "PromptText.Clothing.Hanbok", "value": "hanfu"},
      {"label": "PromptText.Clothing.Cheongsam", "value": "cheongsam"},
      {"label": "PromptText.Clothing.Kimono", "value": "japanses clothes"},
      {"label": "PromptText.Clothing.Sportswear", "value": "sportswear"},
      {"label": "PromptText.Clothing.Workwear", "value": "dungarees"},
      {"label": "PromptText.Clothing.Summer Long Skirt", "value": "summer dress"},
      {"label": "PromptText.Clothing.Pleated skirts", "value": "pleated skirt"},
      {"label": "PromptText.Clothing.Wedding dresses", "value": "wedding dress"},
      {"label": "PromptText.Clothing.Silver dresses", "value": "silvercleavage dress"},
      {"label": "PromptText.Clothing.Hoodie", "value": "hoodie"},
      {"label": "PromptText.Clothing.Long gown", "value": "robe"},
      {"label": "PromptText.Clothing.Apron dresses", "value": "apron"},
      {"label": "PromptText.Clothing.Fur collar", "value": "fur trimmed colla"},
      {"label": "PromptText.Clothing.Hooded cloak", "value": "hooded cloak"},
      {"label": "PromptText.Clothing.Gothic style", "value": "gothic"},
      {"label": "PromptText.Clothing.Jacket", "value": "jacket"},
      {"label": "PromptText.Clothing.Leather Jacket", "value": "leather jacket"},
      {"label": "PromptText.Clothing.Explorer Jacket", "value": "safari jacket"},
      {"label": "PromptText.Clothing.Hood", "value": "hood"},
      {"label": "PromptText.Clothing.Lolita Style", "value": "lolita fashion"},
      {"label": "PromptText.Clothing.Western Style", "value": "western"},
      {"label": "PromptText.Clothing.Denim Jacket", "value": "denim jacket"},
      {"label": "PromptText.Clothing.Turtleneck Jacket", "value": "turtleneck jacket"},
      {"label": "PromptText.Clothing.Firefighter Jacket", "value": "firefighter jacket"},
      {"label": "PromptText.Clothing.Hot pants", "value": "short shorts"},
      {"label": "PromptText.Clothing.Sheer Jacket", "value": "see-through jacket"},
      {"label": "PromptText.Clothing.Swimwear", "value": "swimsuit"},
      {"label": "PromptText.Clothing.Wet body", "value": "wet clothes"},
      {"label": "PromptText.Clothing.One-shoulder", "value": "off_shoulder"},
      {"label": "PromptText.Clothing.Double-shoulder", "value": "bare_shoulders"},
      {"label": "PromptText.Clothing.Plaid", "value": "tartan"},
      {"label": "PromptText.Clothing.Horizontal stripes", "value": "striped"},
      {"label": "PromptText.Clothing.Torn clothes", "value": "torn clothes"},
      {"label": "PromptText.Clothing.Cloak", "value": "armored skirt"},
      {"label": "PromptText.Clothing.Armor", "value": "armor"},
      {"label": "PromptText.Clothing.Metal armor", "value": "metal armor"},
      {"label": "PromptText.Clothing.Berserker armor", "value": "berserker armor"},
      {"label": "PromptText.Clothing.Bikini", "value": "bikini"},
      {"label": "PromptText.Clothing.Dead Pool Water", "value": "Sukumizu"},
      {"label": "PromptText.Clothing.Fast Food Uniform", "value": "fast food uniform"},
      {"label": "PromptText.Clothing.JK Uniform", "value": "JK"},
      {"label": "PromptText.Clothing.Fitness Wear", "value": "gym_uniform"},
      {"label": "PromptText.Clothing.Witch Costume", "value": "miko attire"},
      {"label": "PromptText.Clothing.Trench Coats", "value": "trench coat"},
      {"label": "PromptText.Clothing.Marine Corps Uniform", "value": "SWAT uniform"},
      {"label": "PromptText.Clothing.Pencil Skirt", "value": "pencil skirt"},
      {"label": "PromptText.Clothing.Sleeveless dresses", "value": "sleeveless dress"},
      {"label": "PromptText.Clothing.Belts", "value": "belt"},
      {"label": "PromptText.Clothing.Scarf", "value": "scarf"},
      {"label": "PromptText.Clothing.Leather skirt", "value": "leather skirt"},
      {"label": "PromptText.Clothing.Black leggings", "value": "black leggings"},
      {"label": "PromptText.Clothing.Lab coats", "value": "lab coat"},
      {"label": "PromptText.Clothing.Down jacket", "value": "Down Jackets"},
      {"label": "PromptText.Clothing.Shawl", "value": "cape"},
      {"label": "PromptText.Clothing.Fur shawl", "value": "fur shawl"},
      {"label": "PromptText.Clothing.Bulletproof Armor", "value": "body armor"},
      {"label": "PromptText.Clothing.Bulletproof Vest", "value": "flak jacket"},
      {"label": "PromptText.Clothing.Skirt under kimono", "value": "skirt under kimono"},
      {"label": "PromptText.Clothing.Overcoat", "value": "overcoat"},
      {"label": "PromptText.Clothing.Tweed coat", "value": "duffel coat"},
      {"label": "PromptText.Clothing.Raincoat", "value": "raincoat"},
      {"label": "PromptText.Clothing.Transparent raincoat", "value": "see-through raincoat"},
      {"label": "PromptText.Clothing.Mecha coat", "value": "mech suit"},
      {"label": "PromptText.Clothing.Sorcerer_s Robe", "value": "wizard robe"},
      {"label": "PromptText.Clothing.Assassin attire", "value": "assassin-style"},
    ]},
    {"label": "PromptCategory.Label.Shoes", "prompts": [
      {"label": "PromptText.Shoes.Baseball cap", "value": "Baseball cap"},
      {"label": "PromptText.Shoes.Bare feet", "value": "bare_legs"},
      {"label": "PromptText.Shoes.Boots", "value": "boots"},
      {"label": "PromptText.Shoes.Martin boots", "value": "knee boots"},
      {"label": "PromptText.Shoes.No socks", "value": "no socks"},
      {"label": "PromptText.Shoes.Short socks", "value": "socks"},
      {"label": "PromptText.Shoes.Japanese-style thick-soled socks", "value": "tabi"},
      {"label": "PromptText.Shoes.Stockings", "value": "stockings"},
      {"label": "PromptText.Shoes.Christmas Socks", "value": "christmas stocking"},
      {"label": "PromptText.Shoes.Leg warmers", "value": "leg warmers"},
      {"label": "PromptText.Shoes.Ruffle socks", "value": "frilled socks"},
      {"label": "PromptText.Shoes.Ribbon Trimmed Socks", "value": "ribbon-trimmed legwear"},
      {"label": "PromptText.Shoes.Glitter Socks", "value": "shiny legwear"},
      {"label": "PromptText.Shoes.Ruffled Stockings", "value": "frilled thighhighs"},
      {"label": "PromptText.Shoes.Over-the-knee socks", "value": "thighhighs"},
      {"label": "PromptText.Shoes.Fishnet Socks", "value": "fishnet stockings"},
      {"label": "PromptText.Shoes.Stacked Socks", "value": "loose socks"},
      {"label": "PromptText.Shoes.Leggings", "value": "leggings"},
      {"label": "PromptText.Shoes.Lace leggings", "value": "lace legwear"},
      {"label": "PromptText.Shoes.Ribbed pantyhose", "value": "ribbed legwear"},
      {"label": "PromptText.Shoes.Wet pantyhose", "value": "wet pantyhose"},
      {"label": "PromptText.Shoes.Checked pantyhose", "value": "plaid legwear"},
      {"label": "PromptText.Shoes.See-through pantyhose", "value": "see-through legwear"},
      {"label": "PromptText.Shoes.Pantyhose", "value": "pantyhose"},
      {"label": "PromptText.Shoes.Torn pantyhose", "value": "torn pantyhose"},
      {"label": "PromptText.Shoes.Single leg pantyhose", "value": "single leg pantyhose"},
      {"label": "PromptText.Shoes.Ruffle pantyhose", "value": "frilled pantyhose"},
      {"label": "PromptText.Shoes.Luting garter belts", "value": "studded garter belt"},
      {"label": "PromptText.Shoes.Garter belts", "value": "sock dangle"},
      {"label": "PromptText.Shoes.Thigh ties", "value": "thigh strap"},
      {"label": "PromptText.Shoes.Knitted Caps", "value": "Beanie"},
      {"label": "PromptText.Shoes.Napoleon cap", "value": "Bicorne"},
      {"label": "PromptText.Shoes.Sun Caps", "value": "Boater hat"},
      {"label": "PromptText.Shoes.Sun visor", "value": "Visor cap"},
      {"label": "PromptText.Shoes.Round top hat", "value": "Bowler hat"},
      {"label": "PromptText.Shoes.Newsboy cap", "value": "Cabbie hat"},
      {"label": "PromptText.Shoes.Fisherman_s cap", "value": "Bucket hat"},
      {"label": "PromptText.Shoes.Detective cap", "value": "Fedora"},
      {"label": "PromptText.Shoes.Cowboy hat", "value": "Cowboy hat"},
      {"label": "PromptText.Shoes.Chef hat", "value": "Chef hat"},
      {"label": "PromptText.Shoes.Officer_s cap", "value": "Military hat"},
      {"label": "PromptText.Shoes.Ankle boots", "value": "ankle boots"},
      {"label": "PromptText.Shoes.Lace-up Boots", "value": "cross-laced_footwear"},
      {"label": "PromptText.Shoes.Combat Boots", "value": "combat boots"},
      {"label": "PromptText.Shoes.Armored Boots", "value": "armored boots"},
      {"label": "PromptText.Shoes.Over-the-Knee Boots", "value": "knee boots"},
      {"label": "PromptText.Shoes.Waterproof Rubber Boots", "value": "rubber boots"},
      {"label": "PromptText.Shoes.Leather Boots", "value": "leather boots"},
      {"label": "PromptText.Shoes.Snow Boots", "value": "snow boots"},
      {"label": "PromptText.Shoes.Christmas Boots", "value": "santa boots"},
      {"label": "PromptText.Shoes.Shoes", "value": "shoes"},
      {"label": "PromptText.Shoes.Thick Soled Shoes", "value": "platform footwear"},
      {"label": "PromptText.Shoes.Christmas Hat", "value": "Santa hat"},
      {"label": "PromptText.Shoes.Party Hats", "value": "Party hat"},
      {"label": "PromptText.Shoes.Clown Hats", "value": "Jester cap"},
      {"label": "PromptText.Shoes.Pointy shoes", "value": "pointy footwear"},
      {"label": "PromptText.Shoes.Ballet shoes", "value": "ballet slippers"},
      {"label": "PromptText.Shoes.Sneakers", "value": "sneakers"},
      {"label": "PromptText.Shoes.Safety Caps", "value": "Hardhat"},
      {"label": "PromptText.Shoes.Baseball helmets", "value": "Baseball helmet"},
      {"label": "PromptText.Shoes.Rugby helmets", "value": "Football helmet"},
      {"label": "PromptText.Shoes.Animal helmets", "value": "animal helmet"},
      {"label": "PromptText.Shoes.Roller skates", "value": "roller skates"},
      {"label": "PromptText.Shoes.Skates", "value": "ice skates"},
      {"label": "PromptText.Shoes.Spike Shoes", "value": "spiked shoes"},
      {"label": "PromptText.Shoes.High Heels", "value": "high heels"},
      {"label": "PromptText.Shoes.Mary Jane shoes", "value": "mary janes"},
      {"label": "PromptText.Shoes.Louboutins", "value": "loafers"},
      {"label": "PromptText.Shoes.Women_s student shoes", "value": "uwabaki"},
      {"label": "PromptText.Shoes.Sandals", "value": "sandals"},
      {"label": "PromptText.Shoes.Clogs", "value": "geta"},
      {"label": "PromptText.Shoes.Slippers", "value": "slippers"},
      {"label": "PromptText.Shoes.Flip Flops", "value": "flip-flops"},
      {"label": "PromptText.Shoes.Witch Hat", "value": "witch hat"},
      {"label": "PromptText.Shoes.Beret", "value": "beret"},
      {"label": "PromptText.Shoes.Caps", "value": "peaked cap"},
      {"label": "PromptText.Shoes.Straw hat", "value": "Straw hat"},
      {"label": "PromptText.Shoes.Leg lace ring", "value": "leg_garter"},
      {"label": "PromptText.Shoes.Wrapped legs", "value": "bandaged leg"},
    ]},
    {"label": "PromptCategory.Label.Tail&Wing", "prompts": [
      {"label": "PromptText.Tail&Wing.Pokémon Tails", "value": "pokemon tail"},
      {"label": "PromptText.Tail&Wing.Pikachu tail", "value": "pikachu tail"},
      {"label": "PromptText.Tail&Wing.Otter tail", "value": "otter tail"},
      {"label": "PromptText.Tail&Wing.Scorpion Tail", "value": "scorpion tail"},
      {"label": "PromptText.Tail&Wing.Deer Tail", "value": "deer tail"},
      {"label": "PromptText.Tail&Wing.Weasel Tail", "value": "weasel tail"},
      {"label": "PromptText.Tail&Wing.Alpaca tail", "value": "alpaca tail"},
      {"label": "PromptText.Tail&Wing.Dinosaur tail", "value": "dinosaur tail"},
      {"label": "PromptText.Tail&Wing.Penguin tail", "value": "penguin tail"},
      {"label": "PromptText.Tail&Wing.Sheep tail", "value": "sheep tail"},
      {"label": "PromptText.Tail&Wing.Goat tail", "value": "goat tail"},
      {"label": "PromptText.Tail&Wing.Beaver tail", "value": "beaver tail"},
      {"label": "PromptText.Tail&Wing.Red panda tail", "value": "red panda tail"},
      {"label": "PromptText.Tail&Wing.Jackal tail", "value": "jackal tail"},
      {"label": "PromptText.Tail&Wing.Anteater tail", "value": "anteater tail"},
      {"label": "PromptText.Tail&Wing.Coyote tail", "value": "aardwolf tail"},
      {"label": "PromptText.Tail&Wing.Cheetah tail", "value": "panther tail"},
      {"label": "PromptText.Tail&Wing.Panda tail", "value": "panda tail"},
      {"label": "PromptText.Tail&Wing.Angel tail", "value": "Angel wings"},
      {"label": "PromptText.Tail&Wing.Butterfly Wings", "value": "Butterfly wings"},
      {"label": "PromptText.Tail&Wing.Insect Wings", "value": "insect wings"},
      {"label": "PromptText.Tail&Wing.Bat Wings", "value": "Bat wings"},
      {"label": "PromptText.Tail&Wing.Bird Wings", "value": "bird wings"},
      {"label": "PromptText.Tail&Wing.Feather Wings", "value": "feathered wings"},
      {"label": "PromptText.Tail&Wing.Goblin Wings", "value": "Fairy wings"},
      {"label": "PromptText.Tail&Wing.Dragon Wings", "value": "Dragon wings"},
      {"label": "PromptText.Tail&Wing.Demon Wings", "value": "Demon wings"},
      {"label": "PromptText.Tail&Wing.Flame Wings", "value": "Fiery wings"},
      {"label": "PromptText.Tail&Wing.Mechanical Wings", "value": "Mechanical wings"},
      {"label": "PromptText.Tail&Wing.Ice Wings", "value": "ice crystal texture"},
      {"label": "PromptText.Tail&Wing.Ice and Fire Wings", "value": "((burning feathers)),(feathers_made_of_ice),(frozen feathers),(((ice and fire together)))"},
      {"label": "PromptText.Tail&Wing.Antelope Horns", "value": "antelope horns"},
      {"label": "PromptText.Tail&Wing.Goat Horns", "value": "goat horns"},
      {"label": "PromptText.Tail&Wing.Sheep Horns", "value": "sheep horns"},
      {"label": "PromptText.Tail&Wing.Dairy cow horns", "value": "cow horns"},
      {"label": "PromptText.Tail&Wing.Bull_s horn", "value": "ox horns"},
      {"label": "PromptText.Tail&Wing.Ghost horn", "value": "oni horns"},
      {"label": "PromptText.Tail&Wing.Broken Horn", "value": "broken horn"},
      {"label": "PromptText.Tail&Wing.Mechanical horns", "value": "mechanical horns"},
      {"label": "PromptText.Tail&Wing.Devil_s Horn", "value": "demon horns"},
      {"label": "PromptText.Tail&Wing.Dragon_s Horn", "value": "dragon horns"},
    ]},
    {"label": "PromptCategory.Label.Posture", "prompts": [
      {"label": "PromptText.Posture.Side Sitting", "value": "yokozuwari"},
      {"label": "PromptText.Posture.Shh hand gesture", "value": "shushing"},
      {"label": "PromptText.Posture.Thumbs up", "value": "thumbs up"},
      {"label": "PromptText.Posture.Duck Sitting", "value": "ahirusuwari"},
      {"label": "PromptText.Posture.Stretching legs", "value": "crossed legs"},
      {"label": "PromptText.Posture.cross-legged", "value": "indian style"},
      {"label": "PromptText.Posture.hugging legs", "value": "leg hug"},
      {"label": "PromptText.Posture.kneeling", "value": "kneeling"},
      {"label": "PromptText.Posture.crossed hips", "value": "bent over"},
      {"label": "PromptText.Posture.bowing torso", "value": "arched back"},
      {"label": "PromptText.Posture.showing stomach", "value": "on stomach"},
      {"label": "PromptText.Posture.knee pillow", "value": "lap pillow"},
      {"label": "PromptText.Posture.Hands behind the head", "value": "arms behind head"},
      {"label": "PromptText.Posture.Hands behind the body", "value": "arms behind back"},
      {"label": "PromptText.Posture.Hands on chest", "value": "hand on own chest"},
      {"label": "PromptText.Posture.Cross your arms over your chest", "value": "arms_crossed"},
      {"label": "PromptText.Posture.Lift one leg", "value": "leg_lift"},
      {"label": "PromptText.Posture.Lift both legs", "value": "legs_up"},
      {"label": "PromptText.Posture.Put your hands in your pockets", "value": "hand in pocket"},
      {"label": "PromptText.Posture.Learn to purr like a cat", "value": "paw pose"},
      {"label": "PromptText.Posture.Looking into the distance", "value": "looking afar"},
      {"label": "PromptText.Posture.Looking in the mirror", "value": "looking at mirror"},
      {"label": "PromptText.Posture.Looking at the phone", "value": "looking at phone"},
      {"label": "PromptText.Posture.Looking away", "value": "looking away"},
      {"label": "PromptText.Posture.Looking through bangs", "value": "visible through hair"},
      {"label": "PromptText.Posture.Looking through glasses", "value": "looking over glasses"},
      {"label": "PromptText.Posture.Kneeling on one knee", "value": "one knee"},
      {"label": "PromptText.Posture.Curl up on your side", "value": "fetal position"},
      {"label": "PromptText.Posture.Lie on your back", "value": "on back"},
      {"label": "PromptText.Posture.Lying prone", "value": "on stomach"},
      {"label": "PromptText.Posture.Sitting", "value": "sitting"},
      {"label": "PromptText.Posture.Sitting with knees bent and legs clasped", "value": "hugging own legs"},
      {"label": "PromptText.Posture.Hands in pockets", "value": "hands in pocket"},
      {"label": "PromptText.Posture.Vertical straddling", "value": "upright straddle"},
      {"label": "PromptText.Posture.standing", "value": "standing"},
      {"label": "PromptText.Posture.Squatting", "value": "squatting"},
      {"label": "PromptText.Posture.Interlocking fingers", "value": "interlocked fingers"},
      {"label": "PromptText.Posture.V gesture", "value": "victory pose"},
      {"label": "PromptText.Posture.Hands on the floor", "value": "hand on floor"},
      {"label": "PromptText.Posture.Hand on forehead", "value": "hand on forehead"},
      {"label": "PromptText.Posture.Hand on stomach", "value": "hand on own stomach"},
      {"label": "PromptText.Posture.Hand on shoulder", "value": "arm over shoulder"},
      {"label": "PromptText.Posture.Hand on someone_s leg", "value": "hand on another's leg"},
      {"label": "PromptText.Posture.Hands on someone_s waist", "value": "hand on another's waist"},
      {"label": "PromptText.Posture.Tied to a cross", "value": "crucifixion"},
      {"label": "PromptText.Posture.Legs entwined", "value": "leg lock"},
      {"label": "PromptText.Posture.On all fours", "value": "all fours"},
      {"label": "PromptText.Posture.Wearing headphones", "value": "hand on headphones"},
      {"label": "PromptText.Posture.Ghost pose", "value": "ghost pose"},
      {"label": "PromptText.Posture.Hands clasped together", "value": "own hands clasped"},
      {"label": "PromptText.Posture.Wingspan arms", "value": "wide open arms"},
      {"label": "PromptText.Posture.Facing the viewer", "value": "look at viewer"},
      {"label": "PromptText.Posture.Close to the viewer", "value": "close to viewer"},
      {"label": "PromptText.Posture.Dynamic angle", "value": "dynamic angle "},
      {"label": "PromptText.Posture.Stage angle", "value": "dramatic angle"},
      {"label": "PromptText.Posture.Turning head", "value": "turning around"},
      {"label": "PromptText.Posture.Head tilted", "value": "head tilt"},
      {"label": "PromptText.Posture.Gaze", "value": "stare"},
      {"label": "PromptText.Posture.Looking upward", "value": "looking up"},
      {"label": "PromptText.Posture.Looking down", "value": "looking down"},
      {"label": "PromptText.Posture.Look to the side", "value": "looking to the side"},
      {"label": "PromptText.Posture.Avert your gaze", "value": "looking away"},
      {"label": "PromptText.Posture.Leaning forward", "value": "leaning forward"},
      {"label": "PromptText.Posture.Put your hand to your mouth", "value": "hand to mouth"},
      {"label": "PromptText.Posture.Pistol gesture", "value": "finger gun"},
      {"label": "PromptText.Posture.Cat_s paw gesture", "value": "cat pose"},
    ]},
    {"label": "PromptCategory.Label.Action", "prompts": [
      {"label": "PromptText.Action.Sniffing", "value": "smelling"},
      {"label": "PromptText.Action.Stretching", "value": "stretch"},
      {"label": "PromptText.Action.Cheek resting", "value": "gill support"},
      {"label": "PromptText.Action.Princess hug", "value": "princess carry"},
      {"label": "PromptText.Action.Hugging", "value": "hug"},
      {"label": "PromptText.Action.Back to back", "value": "back-to-back"},
      {"label": "PromptText.Action.Holding hands", "value": "holding hands"},
      {"label": "PromptText.Action.Bathing", "value": "bathing"},
      {"label": "PromptText.Action.Yay", "value": "peace symbol"},
      {"label": "PromptText.Action.Adjusting knee socks", "value": "adjusting_thighhigh"},
      {"label": "PromptText.Action.Hands on hips", "value": "hand on another's hip"},
      {"label": "PromptText.Action.One hand on the waist", "value": "hand_on_hip"},
      {"label": "PromptText.Action.Cross your arms", "value": "hands_on_hips"},
      {"label": "PromptText.Action.Grab", "value": "grabbing"},
      {"label": "PromptText.Action.Hands in the air", "value": "waving"},
      {"label": "PromptText.Action.Handful of hair", "value": "hair scrunchie"},
      {"label": "PromptText.Action.Pull hair", "value": "hair_pull"},
      {"label": "PromptText.Action.Grabbing someone_s hair", "value": "grabbing another's hair"},
      {"label": "PromptText.Action.give the middle finger", "value": "middle_finger"},
      {"label": "PromptText.Action.Bend over", "value": "bent over"},
      {"label": "PromptText.Action.Lifting the blouse", "value": "shirt lift"},
      {"label": "PromptText.Action.Fighting stance", "value": "fighting_stance"},
      {"label": "PromptText.Action.Walk", "value": "walking"},
      {"label": "PromptText.Action.Run", "value": "running"},
      {"label": "PromptText.Action.Cross sitting", "value": "straddling"},
      {"label": "PromptText.Action.Jump", "value": "jump"},
      {"label": "PromptText.Action.Flying", "value": "fly"},
      {"label": "PromptText.Action.Against the wall", "value": "against wall"},
      {"label": "PromptText.Action.Lie", "value": "lie"},
      {"label": "PromptText.Action.Hugging from behind", "value": "hug from behind"},
      {"label": "PromptText.Action.Kissing on the cheek", "value": "kissing cheek"},
      {"label": "PromptText.Action.Kiss on forehead", "value": "kissing forehead"},
      {"label": "PromptText.Action.Kiss on tiptoe", "value": "tiptoe kiss"},
      {"label": "PromptText.Action.Head over fruit", "value": "fruit on head"},
      {"label": "PromptText.Action.Biting gloves", "value": "glove biting"},
      {"label": "PromptText.Action.Face to face", "value": "cheek-to-cheek"},
      {"label": "PromptText.Action.Hand in hand", "value": "hand on another's hand"},
      {"label": "PromptText.Action.Hands crossed", "value": "crossed arms"},
      {"label": "PromptText.Action.Hands open and straight", "value": "spread arms"},
      {"label": "PromptText.Action.Swinging arms", "value": "waving arms"},
      {"label": "PromptText.Action.Extending arms", "value": "outstretched arm"},
      {"label": "PromptText.Action.Support with arms", "value": "carrying"},
      {"label": "PromptText.Action.Wrap your arms around", "value": "arm hug"},
      {"label": "PromptText.Action.Holding", "value": "holding"},
      {"label": "PromptText.Action.Holding a table knife", "value": "holding knife"},
      {"label": "PromptText.Action.Holding a gun", "value": "holding gun"},
      {"label": "PromptText.Action.Holding a cup", "value": "holding cup"},
      {"label": "PromptText.Action.Holding food", "value": "holding food"},
      {"label": "PromptText.Action.Holding a book", "value": "holding book"},
      {"label": "PromptText.Action.With a wand", "value": "holding wand"},
      {"label": "PromptText.Action.Holding an umbrella", "value": "holding umbrella"},
      {"label": "PromptText.Action.Holding a flower", "value": "holding flower"},
      {"label": "PromptText.Action.Holding a microphone", "value": "holding microphone"},
      {"label": "PromptText.Action.Holding objects", "value": "object hug"},
      {"label": "PromptText.Action.Holding a heart", "value": "holding heart"},
      {"label": "PromptText.Action.walking the dog", "value": "walk the dog"},
      {"label": "PromptText.Action.Carrying a skirt", "value": "skirt lift"},
      {"label": "PromptText.Action.taking a dip in a spa", "value": "half body under water"},
      {"label": "PromptText.Action.riding a horse", "value": "horse riding"},
      {"label": "PromptText.Action.taking selfies", "value": "selfie"},
      {"label": "PromptText.Action.One-piece horse", "value": "standing split"},
      {"label": "PromptText.Action.salute", "value": "salute"},
      {"label": "PromptText.Action.Prayer", "value": "pray"},
      {"label": "PromptText.Action.Meditation", "value": "doing a meditation"},
    ]},
    {"label": "PromptCategory.Label.Environment", "prompts": [
      {"label": "PromptText.Environment.Spring", "value": "in spring"},
      {"label": "PromptText.Environment.Summer", "value": "in summer"},
      {"label": "PromptText.Environment.Autumn", "value": "in autumn"},
      {"label": "PromptText.Environment.Winter", "value": "in winter"},
      {"label": "PromptText.Environment.Dusk", "value": "dusk"},
      {"label": "PromptText.Environment.Night", "value": "night"},
      {"label": "PromptText.Environment.Autumn Scene", "value": "(autumn maple forest:1.3),(very few fallen leaves),(path)"},
      {"label": "PromptText.Environment.Sun", "value": "sun"},
      {"label": "PromptText.Environment.Sunset", "value": "sunset"},
      {"label": "PromptText.Environment.Moon", "value": "moon"},
      {"label": "PromptText.Environment.Full Moon", "value": "full_moon"},
      {"label": "PromptText.Environment.Star", "value": "stars"},
      {"label": "PromptText.Environment.Sky", "value": "sky"},
      {"label": "PromptText.Environment.Cloudy", "value": "cloudy"},
      {"label": "PromptText.Environment.Rainy day", "value": "rain"},
      {"label": "PromptText.Environment.Snow and Ice", "value": "snow,ice"},
      {"label": "PromptText.Environment.Snowflakes", "value": "snowflakes"},
      {"label": "PromptText.Environment.Lightning", "value": "lighting"},
      {"label": "PromptText.Environment.Rainbow", "value": "rainbow"},
      {"label": "PromptText.Environment.Meteor Shower", "value": "meteor shower"},
      {"label": "PromptText.Environment.Universe", "value": "universe"},
      {"label": "PromptText.Environment.Sea", "value": "sea"},
      {"label": "PromptText.Environment.Hills", "value": "hills"},
      {"label": "PromptText.Environment.Grassland", "value": "in a meadow"},
      {"label": "PromptText.Environment.Beach", "value": "on the beach"},
      {"label": "PromptText.Environment.In the water", "value": "underwater"},
      {"label": "PromptText.Environment.Seaside", "value": "over the sea"},
      {"label": "PromptText.Environment.Woods", "value": "grove"},
      {"label": "PromptText.Environment.Desert", "value": "on a desert"},
      {"label": "PromptText.Environment.Highland", "value": "plateau"},
      {"label": "PromptText.Environment.Indoor", "value": "indoor"},
      {"label": "PromptText.Environment.Castle", "value": "castle"},
      {"label": "PromptText.Environment.City", "value": "city"},
      {"label": "PromptText.Environment.Water park", "value": "waterpark"},
      {"label": "PromptText.Environment.Carousel", "value": "carousel"},
      {"label": "PromptText.Environment.Ferris wheel", "value": "ferris wheel"},
      {"label": "PromptText.Environment.Aquarium", "value": "aquarium"},
      {"label": "PromptText.Environment.Zoos", "value": "zoo"},
      {"label": "PromptText.Environment.Bowling alley", "value": "bowling alley"},
      {"label": "PromptText.Environment.Art Gallery", "value": "art gallery"},
      {"label": "PromptText.Environment.Museums", "value": "museum"},
      {"label": "PromptText.Environment.Planetarium", "value": "planetarium"},
      {"label": "PromptText.Environment.Swimming Pool", "value": "swimming pool"},
      {"label": "PromptText.Environment.Stadiums", "value": "stadium"},
      {"label": "PromptText.Environment.Temples", "value": "temple"},
      {"label": "PromptText.Environment.Bus Stations", "value": "bus stop"},
      {"label": "PromptText.Environment.Train Station", "value": "train station"},
      {"label": "PromptText.Environment.New Year", "value": "new year"},
      {"label": "PromptText.Environment.Year of the Rabbit", "value": "year of the rabbit"},
      {"label": "PromptText.Environment.Valentine_s Day", "value": "valentine"},
      {"label": "PromptText.Environment.Lantern Festival", "value": "lantern festival"},
      {"label": "PromptText.Environment.Summer Festival", "value": "summer festival"},
      {"label": "PromptText.Environment.Tanabata Festival", "value": "tanabata"},
      {"label": "PromptText.Environment.Mid-Autumn Festival", "value": "mid-autumn festival"},
      {"label": "PromptText.Environment.All Saints_ Day", "value": "halloween"},
      {"label": "PromptText.Environment.Christmas Day", "value": "christmas"},
      {"label": "PromptText.Environment.Curtains", "value": "curtain"},
      {"label": "PromptText.Environment.Bed", "value": "bed"},
      {"label": "PromptText.Environment.Bathroom", "value": "bathroom"},
      {"label": "PromptText.Environment.Toilet cubicle", "value": "toilet stall"},
      {"label": "PromptText.Environment.Geek room", "value": "otaku room"},
      {"label": "PromptText.Environment.Self-catering room", "value": "cafeteria"},
      {"label": "PromptText.Environment.Classroom", "value": "classroom"},
      {"label": "PromptText.Environment.Clubs", "value": "clubroom"},
      {"label": "PromptText.Environment.Saloon", "value": "salon"},
      {"label": "PromptText.Environment.Bar", "value": "bar"},
      {"label": "PromptText.Environment.Izakaya", "value": "izakaya"},
      {"label": "PromptText.Environment.Café", "value": "cafe"},
      {"label": "PromptText.Environment.Bakery", "value": "bakery"},
      {"label": "PromptText.Environment.Convenience store", "value": "convenience store"},
      {"label": "PromptText.Environment.Supermarkets", "value": "supermarket"},
      {"label": "PromptText.Environment.Bookstores", "value": "bookstore"},
      {"label": "PromptText.Environment.Pharmacies", "value": "pharmacy"},
      {"label": "PromptText.Environment.Theaters", "value": "theater"},
      {"label": "PromptText.Environment.Movie theater", "value": "movie theater"},
      {"label": "PromptText.Environment.Conservatory", "value": "greenhouse"},
      {"label": "PromptText.Environment.Basement", "value": "dungeon"},
      {"label": "PromptText.Environment.Gymnasium", "value": "gym"},
      {"label": "PromptText.Environment.Infirmary", "value": "infirmary"},
      {"label": "PromptText.Environment.Laboratory", "value": "laboratory"},
      {"label": "PromptText.Environment.Library", "value": "library"},
      {"label": "PromptText.Environment.Workshops", "value": "workshop"},
      {"label": "PromptText.Environment.Stage", "value": "stage"},
      {"label": "PromptText.Environment.Courtroom", "value": "courtroom"},
      {"label": "PromptText.Environment.Cliff", "value": "cliff"},
      {"label": "PromptText.Environment.Canyon", "value": "canyon"},
      {"label": "PromptText.Environment.Oasis", "value": "oasis"},
      {"label": "PromptText.Environment.Bamboo forest", "value": "bamboo forest"},
      {"label": "PromptText.Environment.Glaciers", "value": "glacier"},
      {"label": "PromptText.Environment.Floating Islands", "value": "floating island"},
      {"label": "PromptText.Environment.Volcanoes", "value": "volcano"},
      {"label": "PromptText.Environment.Savannah", "value": "savanna"},
      {"label": "PromptText.Environment.Waterfalls", "value": "waterfall"},
      {"label": "PromptText.Environment.Streams", "value": "stream"},
      {"label": "PromptText.Environment.Badlands", "value": "wasteland"},
      {"label": "PromptText.Environment.Paddy fields", "value": "rice paddy"},
      {"label": "PromptText.Environment.Wheat Field", "value": "wheat field"},
      {"label": "PromptText.Environment.Flower Field", "value": "flower field"},
      {"label": "PromptText.Environment.Sea of flowers", "value": "flower sea"},
      {"label": "PromptText.Environment.Fountain", "value": "fountain"},
      {"label": "PromptText.Environment.Playgrounds", "value": "playground"},
      {"label": "PromptText.Environment.Market stalls", "value": "market stall"},
      {"label": "PromptText.Environment.Telephone booths", "value": "phone booth"},
      {"label": "PromptText.Environment.Railroad tracks", "value": "railroad tracks"},
      {"label": "PromptText.Environment.Airports", "value": "airport"},
      {"label": "PromptText.Environment.Tunnels", "value": "tunnel"},
      {"label": "PromptText.Environment.Explosion", "value": "explosion"},
      {"label": "PromptText.Environment.Steam", "value": "water vapor"},
      {"label": "PromptText.Environment.Fireworks", "value": "fireworks"},
      {"label": "PromptText.Environment.Floor-to-ceiling windows", "value": "ceiling window"},
      {"label": "PromptText.Environment.Stained Glass", "value": "colourful glass"},
      {"label": "PromptText.Environment.Stained Glass1", "value": "stain glass"},
      {"label": "PromptText.Environment.Graffiti Wall", "value": "Graffiti wall"},
      {"label": "PromptText.Environment.Mosaic Background", "value": "mosaic background"},
      {"label": "PromptText.Environment.Liquid Background", "value": "liquid background, Sputtered water"},
      {"label": "PromptText.Environment.Magic Ring", "value": "magic circles"},
      {"label": "PromptText.Environment.Fluorescent Mushroom Forest", "value": "fluorescent mushroom forests background"},
      {"label": "PromptText.Environment.Colorful Bubbles", "value": "(((colorful bubble)))"},
    ]},
    {"label": "PromptCategory.Label.Style", "prompts": [
      {"label": "PromptText.Style.8bit Game", "value": "8 Bit Game"},
      {"label": "PromptText.Style.80s animation", "value": "1980s anime"},
      {"label": "PromptText.Style.Disney movie", "value": "disney movie"},
      {"label": "PromptText.Style.Gothic Rock", "value": "goth"},
      {"label": "PromptText.Style.80s movie", "value": "80s movie"},
      {"label": "PromptText.Style.Bubble Dragon", "value": "bubble bobble"},
      {"label": "PromptText.Style.Monochrome pictures", "value": "monochrome"},
      {"label": "PromptText.Style.Collage art", "value": "Collage"},
      {"label": "PromptText.Style.Art Nouveau", "value": "((art nouveau))"},
      {"label": "PromptText.Style.Classicalism", "value": "((classicism))"},
      {"label": "PromptText.Style.Futurism", "value": "((futurism))"},
      {"label": "PromptText.Style.Dadaism", "value": "((Dadaism))"},
      {"label": "PromptText.Style.Abstract Art", "value": "((abstract art))"},
      {"label": "PromptText.Style.ASCII Art", "value": "((ASCII art))"},
      {"label": "PromptText.Style.Mousia Style", "value": "((alphonse mucha))"},
      {"label": "PromptText.Style.Monet Style", "value": "((Monet style))"},
      {"label": "PromptText.Style.Contour Light", "value": "rim light"},
      {"label": "PromptText.Style.Volumetric Light", "value": "Volumetric Lighting"},
      {"label": "PromptText.Style.Neon Light", "value": "glowing neon lights"},
      {"label": "PromptText.Style.Cinematic Light", "value": "Cinematic Lighting"},
      {"label": "PromptText.Style.Stained Glass Process", "value": "Dalle de verre"},
      {"label": "PromptText.Style.Pixel painting", "value": "pixel art"},
      {"label": "PromptText.Style.Porcelain painting", "value": "Encaustic painting"},
      {"label": "PromptText.Style.Ink Painting", "value": "Ink wash painting"},
      {"label": "PromptText.Style.Copperplate engraving", "value": "Mezzotint"},
      {"label": "PromptText.Style.Pixar animation", "value": "style of Pixar"},
      {"label": "PromptText.Style.Polaroid Art", "value": "Polaroid art"},
      {"label": "PromptText.Style.Kaleidoscope Photography", "value": "Kaleidoscope Photography"},
      {"label": "PromptText.Style.Opal Rendering", "value": "opal render"},
      {"label": "PromptText.Style.Chromatogram", "value": "chemigram"},
      {"label": "PromptText.Style.Lens Glow", "value": "lens flare"},
      {"label": "PromptText.Style.Metallic Shine", "value": "metallic luster"},
      {"label": "PromptText.Style.Ghibli style", "value": "Studio Ghibli"},
      {"label": "PromptText.Style.Fantasy", "value": "dreamlike"},
      {"label": "PromptText.Style.Signature style", "value": "(faux traditional media)"},
      {"label": "PromptText.Style.Original god impact", "value": "genshin impact"},
      {"label": "PromptText.Style.Beyblue Line", "value": "azur lane"},
      {"label": "PromptText.Style.Fleet Collection", "value": "kantai collection"},
      {"label": "PromptText.Style.Edge Walker", "value": "rebecca (cyberpunk) "},
      {"label": "PromptText.Style.Chainsaw Man", "value": "chainsaw man"},
      {"label": "PromptText.Style.Magic Vortex", "value": "Magic Vortex"},
      {"label": "PromptText.Style.Diesel Punk", "value": "((dieselpunk))"},
      {"label": "PromptText.Style.Four Grams", "value": "4koma"},
      {"label": "PromptText.Style.Magazine Scans", "value": "magazine scan"},
      {"label": "PromptText.Style.Album Cover", "value": "album cover"},
      {"label": "PromptText.Style.Line Thickening", "value": " (lineart)"},
      {"label": "PromptText.Style.Steamwave", "value": "synthwave"},
      {"label": "PromptText.Style.Rococo", "value": "(illustration),(paper figure),(lococo),((impasto)),(shiny skin)"},
      {"label": "PromptText.Style.Silhouette", "value": "silhouette"},
      {"label": "PromptText.Style.Illustration", "value": "illustration"},
      {"label": "PromptText.Style.Watercolor", "value": "(((ink))), ((watercolor))"},
      {"label": "PromptText.Style.Ukiyo-e", "value": "illustration,(((ukiyoe))),((sketch)),((japanese_art))"},
      {"label": "PromptText.Style.Chinoiserie", "value": "((wash painting)),((ink splashing)),((color splashing)),((((dyeing)))),((chinese style))"},
      {"label": "PromptText.Style.Ambient Light", "value": "moody lighting"},
      {"label": "PromptText.Style.Tyndall effect", "value": "Tyndall effect"},
      {"label": "PromptText.Style.Light Leakage Light Effect", "value": "light leaks"},
      {"label": "PromptText.Style.Background Light", "value": "background light"},
      {"label": "PromptText.Style.Natural Light", "value": "available light"},
      {"label": "PromptText.Style.Oil painting", "value": "((dyeing)),((oil painting)),((impasto))"},
      {"label": "PromptText.Style.Black and white sketches", "value": " (posing sketch), (monochrome)"},
      {"label": "PromptText.Style.Hand sketches", "value": "sketch"},
      {"label": "PromptText.Style.Pencil sketches", "value": "(monochrome), (gray scale), (pencil sketch lines"},
      {"label": "PromptText.Style.Colored pencil drawing", "value": "(watercolor pencil)"},
    ]},
    {"label": "PromptCategory.Label.Magic", "prompts": [
      {"label": "PromptText.Magic.Water magic", "value": "((water drops)),wet clothes,((beautiful detailed water)),((floating)),dynamic angle"},
      {"label": "PromptText.Magic.Ice magic", "value": "beautiful detailed glow, (detailed ice), beautiful detailed water"},
      {"label": "PromptText.Magic.Ice change", "value": "beautiful detailed glow,detailed ice,beautiful detailed water,(floating palaces:1.2),(ice crystal texture wings),（Iridescence and rainbow hair:2.5）"},
      {"label": "PromptText.Magic.Star ice music", "value": "beautiful detailed glow,detailed ice,beautiful detailed water, (floating palaces:1.3),(((ice crystal texture wings)))"},
      {"label": "PromptText.Magic.Forest Ice", "value": "((detailed beautiful snow forest with trees)), ((snowflakes)), floating"},
      {"label": "PromptText.Magic.Crystallization method", "value": "(((crystals texture Hair))),((beautiful detailed glass hair)),((glass shaped texture hand)),((crystallize texture body)),gem body,hands as clear as jewels,crystallization of clothes,((crystals texture skin)),sparkle, lens flare, light leaks,broken glass,detailed glass shaped clothes,beautiful detailed gemstone sky, gemstone sea, crystals texture flowers,((detailed crystallized clothing))"},
      {"label": "PromptText.Magic.Nuclear explosion method", "value": "beautiful detailed glow,((flames of war)),(((nuclear explosion behide)))"},
      {"label": "PromptText.Magic.Wind Magic", "value": "((breeze)), flying splashes,  flying petals, wind"},
      {"label": "PromptText.Magic.Quicksand Law", "value": "((surrounded by heavy floating sand flow and floating sharp stones)),((((ink)))),((illustration)),((watercolor))"},
      {"label": "PromptText.Magic.Thunder and Lightning", "value": " (detailed light), ((lightning in hand)),lightning surrounds,(((lightning chain)))"},
      {"label": "PromptText.Magic.Holy light method", "value": "(sunlight),(angel),dynamic angle, floating, wing, halo, floating white silk,(Holy Light),silver stars"},
      {"label": "PromptText.Magic.Reed Name Law", "value": "beautiful detailed pampas grass field, open hakama, surrounded by floating sakura, yellow full moon, beautiful detailed dark midnight sky, messy white long hair"},
      {"label": "PromptText.Magic.Nature Law", "value": "beautiful and delicate water, the finest grass, very delicate light, nature, painting, water spray, breeze, flowers and grass meadow, near the water edge, (sunset, starry sky in a circle), randomly distributed clouds, river, splashing water, falling petals"},
      {"label": "PromptText.Magic.Forest method", "value": "(detailed light) , feather, leaves, nature, (sunlight), river, (forest),(bloom)"},
      {"label": "PromptText.Magic.Iridescence Law", "value": "floating and rainbow long hair,Iridescence and rainbow, beautiful detailed starry sky"},
      {"label": "PromptText.Magic.Dark Lock Method", "value": "chain ring, chain storm, dark chain,((wholeblack bloomer)), darkside, night, deep dark, darkness, ((dark clouds)),((ruins)),shadow, death garden"},
      {"label": "PromptText.Magic.Fire Cloud Method", "value": "beautiful detailed glow, floating ashes, beautiful and detailed explosion, red moon, fire, fire cloud, wings on fire, a cloudy sky, smoke of gunpowder, burning, black dress, dove of peace, (floating cloud:1.2)"},
      {"label": "PromptText.Magic.Castle Method", "value": "beautiful detailed glow, detailed ice, beautiful detailed water, (magic circle:1.2), (floating palaces:1.3)"},
      {"label": "PromptText.Magic.Dusk method", "value": "(water bloom), (delicate glow),  (breeze), long   Flowers meadow,(((sunset)), (less stars form a circle), randomly distributed clouds, (rivers), (willows with branches falling into the water)"},
      {"label": "PromptText.Magic.Bubble method", "value": "(((colorful bubble))),(floating),detailed light"},
      {"label": "PromptText.Magic.Rose method", "value": "((rose)), (vine), cage, bandage, red rope, (detail light), falling rose petals"},
      {"label": "PromptText.Magic.Star method", "value": "(starry tornado:1.4), starry Nebula, beautiful detailed sky"},
      {"label": "PromptText.Magic.Moon method", "value": "((moon)), starry sky, (lighting particle), fog, snow,(bloom)"},
      {"label": "PromptText.Magic.Snow Moon Method", "value": "beautiful detailed glow, detailed ice, beautiful detailed water, (cold full moon), snowflake, (floating cloud:1.2)"},
      {"label": "PromptText.Magic.Forest Fire Method", "value": "((burning forest)), spark, light leaks, burning sky, flame, flames burning around, (flying sparks)"},
      {"label": "PromptText.Magic.Waste Land Law", "value": "((destroyed)),explosion, buildings in disarray, The residual eaves DuanBi, cumulus, mouldy, floating, wind, Dead end machine,(broken robot),(Mechanical robot girl), in the rubble of a devastated city"},
      {"label": "PromptText.Magic.Battle Armor Method", "value": "mecha clothes, robot girl, sliver bodysuit,((sliver)) and (broken) body"},
      {"label": "PromptText.Magic.Gold Method", "value": "Extremely gorgeous metal style, Metal crown with ornate stripes, Various metals background, Sputtered molten iron, floating hair, Hair like melted metal, Clothes made of silver, Clothes with gold lace, flowing gold and silver, everything flowing and melt, flowing iron, flowing silver, lace flowing and melt"},
      {"label": "PromptText.Magic.Machine Girl Method", "value": "mecha clothes, robot girl"},
      {"label": "PromptText.Magic.Necromancy", "value": "ink,(((bone))), (((ribs))), rose, black hair, blue eyes, greyscale, no shadow, simple background, bright skin"},
      {"label": "PromptText.Magic.Crystal method", "value": "(((gorgeous crystal armor))),(((crystal wings))),((altocumulus)),(clear_sky),(snow mountain),((flowery flowers)),(flowery bubbles),cloud map plane, crystal, crystal poppies,Brilliant light, thick_coating, glass tint,(watercolor)"},
      {"label": "PromptText.Magic.Suisen Method", "value": "((an extremely delicate and beautiful)),floating, (detailed wet clothes), (detailed light),feather, nature, (sunlight), river, floating palace, beautiful and delicate water,(bloom),(shine)"},
      {"label": "PromptText.Magic.Ice and Fire", "value": "(blue spark),(red and blue hair),blue eyes, burning sky,flame,Rainbow in the sky,((Flames burning ice)),(((fire  butterflies))),(((ice crystal texture wings))),(Flying sparks),(detailed ice),((a lot of luminous ice crystals)),((burning feathers)),(feathers made of ice),(frozen feathers),(((ice and fire together)))"},
      {"label": "PromptText.Magic.Dragon Rider", "value": "(anger), dragon horns, (silver armor), metal, complex pattern, cape, indifference"},
      {"label": "PromptText.Magic.Falling method", "value": "((full body)),(helpless),tear, crying,(((((falling from the sky))))),((Weathering With You)),((falling)),((face towards the sky))，(hair flows upwards),((disheveled hair)),(1 girl), floating, beautiful detailed sky"},
      {"label": "PromptText.Magic.Underwater Law", "value": "((underwater)),(beautiful detailed water),((coral)),dynamic angle, floating,(detailed light),floating hair,(splash),((fishes)),leaves dress, feather, nature,(sunlight),(underwater forest),(bloom),(detailed glow),drenched, seaweed, fish,(((Tyndall effect)))"},
      {"label": "PromptText.Magic.Secret World Method", "value": "(extremely detailed CG unity 8k wallpaper),(((masterpiece))), (((best quality))), ((ultra-detailed)), (best illustration),(best shadow), ((an extremely delicate and beautiful)),dynamic angle,floating, fairyland,dynamic angle,sea of flowers,beautiful detailed garden,wind,classic,spring, (detailed light),feather, nature, (sunlight), river, forest,(((floating palace))),((the best building)),beautiful and delicate water,(painting),(sketch),(bloom),(shine)"},
      {"label": "PromptText.Magic.Photography method", "value": "(((masterpiece))), ((the best quality, super fine illustrations, beautiful and delicate water)), ((very delicate light)), ((nature, painting)), ((fine lighting, more transparent stars, high-quality snowflakes, high-quality mountains, very fine 8KCG wallpapers)), (plateau), (((snow mountain))), sunrise, randomly distributed clouds, (snow field), cliff, ((rotating star sky)), ((lake in mountain stream)), luminous particles"},
      {"label": "PromptText.Magic.Modern Method", "value": "1980s (style),simple background, retro artstyle"},
      {"label": "PromptText.Magic.Blood magic", "value": "(white hair), red long hair, red eyes, (full body), (((with sword))), angry face, (beautiful detailed eyes), Blood drop,Blood fog, floating hair, disheveled hair,  Splashing blood,(Bloodstain)"},
      {"label": "PromptText.Magic.Dragon Magic", "value": "((dragon)), ((dragon background))"},
      {"label": "PromptText.Magic.War Maiden Method", "value": "hair fluttering in the wind,((mechanical arm armor)),((mechanical body armor)),riding motor, bodysuit,((ruins of city in war, fire, burning cars, burning buildings)),air force fleet in the sky"},
      {"label": "PromptText.Magic.Dragon machine method", "value": "mecha clothes, robot girl, sliver bodysuit, dragon wings, ((a dragon  stands behind the girl)), beautiful detailed sliver dragon armor"},
      {"label": "PromptText.Magic.Star Butterfly", "value": "((Beautiful butterflies in detail)),((Beautiful stars in detail)),(((halter dress ))),particle,(Starry sky in beautiful detail),(Hazy fog),(Ruins of beautiful details),(((Standing on the surface of the sea)))"},
      {"label": "PromptText.Magic.Academy Method", "value": "blonde wavy hair, (shiny long hair), ((Gothic Lolita)), blue white skirt, ((short skirt)), black Headdress, bowknot, (((hair ornament))), (hair flower), Lace, cross-laced footwear, ribbon-trimmed sleeves, building architecture, ((gothic architecture)), starry sky, outdoors, church, (castle) "},
      {"label": "PromptText.Magic.Hoshi Haikai", "value": "walking, waves, wind,(((glistening light of waves))),(detailed sunset glow),(floating flow),((coral)),(Luminous),coast,(floating colorful bubbles),beautiful detailed sky,(fluorescence),detailed shadow,(conch),beautiful detailed water, starfish, meteor, rainbow,(seabirds),(glinting stars), (glowworm),(splash),detailed cloud, shell,(fireworks)"},
      {"label": "PromptText.Magic.Winter Snow Method", "value": "beautiful detailed sky, night, stars, (red plum blossom),((winter)),(((snowflakes))), ((red and white flowers))，(starry sky),(sitting),((colorful)),scenery, lantern,(starfall)"},
    ]}
  ]